language: node_js

node_js:
  - '6.9.5'

before_install:
  - npm install -g jspm

before_script:
  - jspm -v
  - jspm i -y
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email:
    on_success: change
    on_failure: change

script:
  - npm test
  - npm run lint
